apiVersion: v1
kind: Template
labels:
  template: redis
metadata:
  annotations:
    description: A redis instance
    tags: redis
  creationTimestamp: null
  name: redis
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: ${REDIS_SERVICE_NAME}
    name: ${REDIS_SERVICE_NAME}
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: redis:latest
      from:
        kind: DockerImage
        name: redis:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${REDIS_SERVICE_NAME}
    name: ${REDIS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      app: ${REDIS_SERVICE_NAME}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${REDIS_SERVICE_NAME}
      spec:
        containers:
        - image: redis:latest
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /data
            name: redis-data
        volumes:
        - emptyDir: {}
          name: redis-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: ${REDIS_SERVICE_NAME}:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${REDIS_SERVICE_NAME}
    name: ${REDIS_SERVICE_NAME}
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: ${REDIS_SERVICE_NAME}
  status:
    loadBalancer: {}
parameters:
- name: REDIS_SERVICE_NAME
  displayName: Redis Service Name
  value: redis
